---
- name: Install and configure tomcat server for deployment
  hosts: nodes
  remote_user: root

  vars:
    tomcat_version: 10.1.5
    tomcat_user: tomcat
    tomcat_path: /opt/tomcat
    tomcat_group: tomcat


  tasks:
    - name: Update system package
      apt:
       upgrade: yes
       update_cache: yes

    - name: Install Java
      apt:
       name: openjdk-11-jdk
       state: present

    - name: Check Java Version
      command: java --version

    - name: Create Tomcat User
      user:
       name: '{{ tomcat_user }}'

    - name: Create Tomcat Group
      group:
       name: '{{ tomcat_group }}'

    - name: Create Tomcat Directory
      file:
       path: '{{ tomcat_path }}'
       owner: '{{ tomcat_user }}'
       group: '{{ tomcat_group }}'
       mode: 755
       recurse: yes

    - name: Download Tomcat and Unarchive
      unarchive:
   #    src: "https://archive.apache.org/dist/tomcat/tomcat-10/v10.1.5/bin/apache-tomcat-10.1.5.tar.gz"
       src: "https://archive.apache.org/dist/tomcat/tomcat-10/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
       dest: '{{ tomcat_path }}'
       remote_src: yes
       extra_opts: [--strip-components=1]

    - name: Change ownership of tomcat folder
      file:
       path: '{{ tomcat_path }}'


    - name: Start tomcat Server
      command: nohup {{ tomcat_path }}/bin/startup.sh
   #  command: sh {{ tomcat_path }}/bin/startup.sh

    - name: Allow tcp connections
      command: sudo ufw allow 8080/tcp

    - name: Connect to Tomcat on port 8080
      tags: test
      uri:
       url: http://localhost:8080
      register: result
      until: "result.status==200"
      retries: 2
      delay: 5
      notify:
        - Echo connection

  handlers:
     - name: Echo connection
       command: echo "success"              